### ISSUE TITLE
Version-related error on load

### ISSUE THREAD

**Issue by MarioSMB** [snackerpirater/ConstructsCasting#4]
![2024-08-15_00 07 40](https://github.com/user-attachments/assets/8206d19d-8be8-4bac-8312-f558f475acef)

**Comment by snackerpirater** [comment]
Intended behavior, as I have not gotten around to updating the mod yet.

**Comment by MarioSMB** [comment]
I see, that’s fair - at first I thought it maybe wasn’t recognising the .0 in the version!  
Will close this issue so as to not apply any artificial pressure.  

Looking forward to trying it out in the future, thanks!
